package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Friday, June 6, 2014 7:32:58 PM ICT
*/

public interface HelloOperations 
{
  String echoString (String mesg);
} // interface HelloOperations
